'use client'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TranslationProvider, useTranslation } from "../app/Translations/TranslationContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

function LocaleWrapper({ children }: { children: React.ReactNode }) {
  const { locale } = useTranslation();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${locale === "ar" ? "font-arabic" : "font-default"}`}
      >
        {children}</body>
    </html>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <TranslationProvider>
      <LocaleWrapper>{children}</LocaleWrapper>
    </TranslationProvider>
  );
}
